### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by AvivSham** [VITA-Group/SinNeRF#1]
Hi All,
Thank you for this repo and amazing paper!
Do you plan to release the training code anytime soon? (we would love that!)

Thanks.
@avivnavon

**Comment by Ir1d** [comment]
@AvivSham Thanks for your interest. I'm tidying up the codes and trying to refactor them. I will release them soon. Hopefully, I can finish by next week but no later than the end of April.

**Comment by AvivSham** [comment]
@Ir1d  Thank you for responding. 
Can you please remain this issue open? In addition, how can I be notified once the code is released?
@AvivNavon

**Comment by Ir1d** [comment]
I will ping you in this issue and close the issue once the code is released

**Comment by Ir1d** [comment]
Hi @AvivSham the code is ready now. Thanks for your patience.
