### ISSUE TITLE
Some minor issues and loss=nan problem

### ISSUE THREAD

**Issue by happysxpp** [VITA-Group/SinNeRF#11]
Hi, there！Sorry to reply you so late, I have been reading your code and running experiments recently.

But I ran into some small problems as follows,

**1. When running the test code, the following code will make an error**
```
python eval.py  \
       --dataset_name blender_ray_patch_1image_rot3d  \
       --root_dir ./synthetic_SinNeRF/lego/  \
       --N_importance 64 --img_wh 400 400 --model nerf \
       --ckpt_path ./ckpts/lego_s6_4ft/last.ckpt \
       --timestamp test
``` 
When the default value of the `--split` is `test`, an error will be reported here. note that `frame`
https://github.com/VITA-Group/SinNeRF/blob/6f101f924fe9ba7793df5a9bbc52b2c82423e251/datasets/blender_ray_patch_1image_rot3d.py#L540

---

**2. The dtu file you uploaded is missing a part or the code is wrong?**
![image](https://user-images.githubusercontent.com/107449513/179335872-a107cc8c-a96d-4483-9def-72943e0f8c06.png)
https://github.com/VITA-Group/SinNeRF/blob/6f101f924fe9ba7793df5a9bbc52b2c82423e251/datasets/dtu_proj.py#L433-L434

---

**3. loss nan problem**
I am running the latest code on an RTX 3090, 24G, and environments are created using `environment.yaml`, but is still OOM, so I adjusted the `patch_size`, `precision` and `--sH`, `--sW` according to the README.

I set `precision=16`, and `--sH`, `--sW` remain the same(=6).  

I found that the loss=nan problem will appear when the patch_size is too small, such as `patch_size=8` or `patch_size=16`, even `patch_size=32`.  

It works(without loss=nan) when `patch_size=50`, but that's not a good number is it?  

  
  

I would be grateful if you could provide advice on how to deal with this. 
Thank you !

**Comment by Ir1d** [comment]
Thanks for your interest and experiments! Feel free to let me know if there are other issues.
1. For lego please use `--split val`, I'll update the readme
2. https://drive.google.com/drive/folders/13Lc79Ox0k9Ih2o0Y9e_g_ky41Nx40eJw depth can be downloaded here
3. I also notice that when using precision=16, sometimes there will be loss=nan issue. I think as long as patch_size * sH (or sW) covers the majority region of the image, it should work well. If patch_size=8 and sH=6, then the patches fed into the DINO-ViT only covers a local region. Maybe when reducing the patch_size, you should enlarge the strides (sH and sW).

**Comment by happysxpp** [comment]
Sure, will try your suggestion. 

Thank you for your reply, it is very helpful!! :)

**Comment by stevehan00** [comment]
@happysxpp How long did it take for whole trianing stages each scene on RTX 3090, approximately?

**Comment by happysxpp** [comment]
@h5jam Hi, 

Each epoch is about 1m 30s. Therefore in my experiment(lego), 4000 epoch(step1 + step2) ≈ 4day.

I hope it'll help you.

**Comment by stevehan00** [comment]
Thank you!

**Comment by HannahHaensen** [comment]
> Hi, there！Sorry to reply you so late, I have been reading your code and running experiments recently.
> 
> But I ran into some small problems as follows,
> 
> **1. When running the test code, the following code will make an error**
> 
> ```
> python eval.py  \
>        --dataset_name blender_ray_patch_1image_rot3d  \
>        --root_dir ./synthetic_SinNeRF/lego/  \
>        --N_importance 64 --img_wh 400 400 --model nerf \
>        --ckpt_path ./ckpts/lego_s6_4ft/last.ckpt \
>        --timestamp test
> ```
> 
> When the default value of the `--split` is `test`, an error will be reported here. note that `frame`
> 
> https://github.com/VITA-Group/SinNeRF/blob/6f101f924fe9ba7793df5a9bbc52b2c82423e251/datasets/blender_ray_patch_1image_rot3d.py#L540
> 
> **2. The dtu file you uploaded is missing a part or the code is wrong?** ![image](https://user-images.githubusercontent.com/107449513/179335872-a107cc8c-a96d-4483-9def-72943e0f8c06.png)
> 
> https://github.com/VITA-Group/SinNeRF/blob/6f101f924fe9ba7793df5a9bbc52b2c82423e251/datasets/dtu_proj.py#L433-L434
> 
> **3. loss nan problem** I am running the latest code on an RTX 3090, 24G, and environments are created using `environment.yaml`, but is still OOM, so I adjusted the `patch_size`, `precision` and `--sH`, `--sW` according to the README.
> 
> I set `precision=16`, and `--sH`, `--sW` remain the same(=6).
> 
> I found that the loss=nan problem will appear when the patch_size is too small, such as `patch_size=8` or `patch_size=16`, even `patch_size=32`.
> 
> It works(without loss=nan) when `patch_size=50`, but that's not a good number is it?
> 
> I would be grateful if you could provide advice on how to deal with this. Thank you !

I am training on a 3090 too, I did not face the issue with the nan loss for the lego but for an own dataset, have you tips on how to solve the nan issue, what was your final config?

**Comment by happysxpp** [comment]
@HannahHaensen Hi,

I set `--patch_size 56 --sW 8 --sH 8`, others remain the same.

Since then, I have not continued to study this paper in depth. So I can't offer much help.

**Comment by Ir1d** [comment]
@HannahHaensen For custom images, if the depth contains a lot of zeros, there are chances of nan as well. You can considering masking out the zero depth regions
