### ISSUE TITLE
nan

### ISSUE THREAD

**Issue by xiaoyudanaa** [VITA-Group/SinNeRF#13]
I'm sorry to bother you.
I'm having some problems running your code on my own machine and I hope you can help me out (I'm using 4 A5000 cards for training. Other than that, all other parameters are default).
1, in the NeRF synthetic dataset on step1 training, in the training to more than 1500 steps, all the losses become 'nan', is this normal?
2, after this situation of 1, does it mean that the model has been trained? Should I stop the training?
3, There are several different pth files in the 'ckpts/lego_s6' folder, which one should I choose as the training weights for the second step?
4、You mentioned supplementary material in your paper, but I didn't find the relevant link, can you provide it?
I am looking forward to your reply, thank you very much.

**Comment by xiaoyudanaa** [comment]
![image](https://user-images.githubusercontent.com/77732714/191427721-fbc15484-a7a3-4461-bb04-ed21fa8aa1e4.png)
第一轮运行完后产生了这三个ckpt文件，我该用哪个运行第二轮呀
下面是产生的csv表格：
![image](https://user-images.githubusercontent.com/77732714/191428239-a1a8f02b-3dd6-4b31-a6e2-2df4d11d64a0.png)
下面是我运行eval.py对这三个ckpt，产生的结果：
![image](https://user-images.githubusercontent.com/77732714/191432946-23edc4ff-2b45-4058-8384-d8db643f492f.png)
顺便想问您一下，怎么打印SSIM和LPIPS这两个评价指标呀？我不太会，希望您能教教我。万分感谢

**Comment by Ir1d** [comment]
Hi @xiaoyudanaa ,

1. in the training to more than 1500 steps, all the losses become 'nan'.

This is weird.. If you run again, does this happen again?

2. does it mean that the model has been trained?

It means that the model is broken. We should restart the training.

3. There are several different pth files in the 'ckpts/lego_s6' folder, which one should I choose as the training weights for the second step

You can use the latest or use the one with the best PSNR (the filename can be found in logs)

For example in the screenshot, you can use epoch=1059.ckpt

4. supplementary material.

Everything in the supplementary is available in the latest draft and code. Is there anything you'd like to know in particular? 

5.  SSIM, Lpips

I calculated these two metrics offline. You can google for some handy implementations.

**Comment by xiaoyudanaa** [comment]
> Hi @xiaoyudanaa ,
> 
> 1. in the training to more than 1500 steps, all the losses become 'nan'.
> 
> This is weird.. If you run again, does this happen again?
> 
> 2. does it mean that the model has been trained?
> 
> It means that the model is broken. We should restart the training.
> 
> 3. There are several different pth files in the 'ckpts/lego_s6' folder, which one should I choose as the training weights for the second step
> 
> You can use the latest or use the one with the best PSNR (the filename can be found in logs)
> 
> For example in the screenshot, you can use epoch=1059.ckpt
> 
> 4. supplementary material.
> 
> Everything in the supplementary is available in the latest draft and code. Is there anything you'd like to know in particular?
> 
> 5. SSIM, Lpips
> 
> I calculated these two metrics offline. You can google for some handy implementations.
您的回答真的使太细致了，非常感谢。我可以加一下您的微信嘛，我的微信号是：Weafree

**Comment by Ir1d** [comment]
You can reach me via email

**Comment by HannahHaensen** [comment]
when running evaluation like this: 

`python eval.py  --dataset_name llff  --root_dir /home/hannah/Documents/GitHub/SinNeRF/datasets/nerf_llff_data/room --N_importance 64 --img_wh 504 378 --model nerf --ckpt_path ckpts/room.ckpt --timestamp test`

neither PSNR nor SSIM or LPIPS ar provided in the results just the final gif is produced is there another script for these metrics or is it just adapting the eval script

**Comment by Ir1d** [comment]
@HannahHaensen I think i didn't calculate psnr, ssim in eval.py. I generated the images and calculated offline.
