### ISSUE TITLE
How do you get the depth maps of RGB images like LLFF

### ISSUE THREAD

**Issue by tmpss93172** [VITA-Group/SinNeRF#14]
Hi, thanks for the great work!

I want to know how you got the depth maps in your datasets.
As far as I know, some original datasets like LLFF do not provide depth information.

Thanks!

**Comment by Ir1d** [comment]
Hi @tmpss93172, for the ECCV submission, we used a pre-trained nerf to obtain the depth. We're also working on improving the framework to work with monocular depth estimators. Thanks!

**Comment by tmpss93172** [comment]
Got it. Thank you so much!
