### ISSUE TITLE
How to get the depth map

### ISSUE THREAD

**Issue by yuchen-ji** [VITA-Group/SinNeRF#15]
Hello，
I want to ask the approach to get the depth map?

**Comment by Ir1d** [comment]
I will release updates to train SinNeRF with monocular depth soon. Currently, for NeRF synthetic and LLFF, we use a pre-trained NeRF to obtain the depth. For DTU, we use MVSNet_pytorch to obtain the depth.

**Comment by yuchen-ji** [comment]
Thanks for your reply！
I want to ask what is the definition of depth of depth map.
Is it the distance from the object surface to the camera focus (along the ray) ?
OR the distance between the object surface and this pixel (vertical distance) ？
