### ISSUE TITLE
quadratic images and depth of synthetic dataset

### ISSUE THREAD

**Issue by HannahHaensen** [VITA-Group/SinNeRF#16]
does nerf synthetic (own synthetic data) has to be quadratic? is there a specific reason for that check in the code?

**Comment by HannahHaensen** [comment]
and another question about the synthetic dataset:

`self.ref_depth = np.load(os.path.join(self.root_dir, 'depth_nerf', os.path.basename(self.image_paths[self.ref_idx])).replace('.JPG', '.npy').replace('.png', '.npy'))`
                        
why is only that one depth image loaded e.g. for lego the one ending with 20?

``` 
if 'lego' in self.root_dir:
      self.ref_idx = 20
``` 

thanks in advance :)

**Comment by Ir1d** [comment]
> does nerf synthetic (own synthetic data) has to be quadratic? is there a specific reason for that check in the code?

This is not required afaik. I think it's some legacy code from nerf_pl

> why is only that one depth image loaded e.g. for lego the one ending with 20?

Our setting only involves one depth. for lego it's 20 because it covers the major regions of the scene

**Comment by HannahHaensen** [comment]
@Ir1d thank you very much for your reply!

so this depth is used as the image 20 covers "the most" regions for the lego part ? even though the angle varies in other images? can you elaborate a bit on that?

**Comment by Ir1d** [comment]
> so this depth is used as the image 20 covers "the most" regions for the lego part

Yes

> even though the angle varies in other images? 

I don't really understand this question.
