### ISSUE TITLE
Question about angle variable

### ISSUE THREAD

**Issue by HannahHaensen** [VITA-Group/SinNeRF#18]
I have a question about the blender dataset. the dataset definition contains the value 30, what does this angle indicate?

```
class Blender_ray_patch_1image_rot3d_camera_Dataset(Dataset):
    def __init__(self, root_dir, split='train', img_wh=(400, 400), patch_size=-1, factor=1, test_crop=False, with_ref=False, repeat=1, load_depth=False, depth_type='nerf', sH=1, sW=1, angle=30, **kwargs):
```

**Comment by Ir1d** [comment]
It specifies the max distance between novel views and the given reference view. Suppose ref view is 0, then novel views lie in [-30, 30]
