### ISSUE TITLE
Regarding results in the table 2

### ISSUE THREAD

**Issue by ayclove** [VITA-Group/SinNeRF#19]
Thank you so much for sharing your great work.
Regarding the results in table 2, I have the below questions.

Q1. Which scenes did you use for the evaluation and what is the reference camera ID?
According to the files and codes, I am assuming that you evaluated on 19 scenes, such as below,
[1, 3, 4, 5, 6, 8, 9, 14, 15, 30, 34, 40, 55, 60, 63, 82, 84, 103, 105]
Please correct me if I am wrong.

Q2. Did you use any object mask for the evaluation as RegNeRF did?
If so, would you please let me know how you created the mask?

Thank you very much for your kind reply in advance.

**Comment by Ir1d** [comment]
Hi @ayclove 

Q1: Yes that's correct. Thanks for pointing out!

Q2; No we didn't use any mask for evaluation
