### ISSUE TITLE
About paper results

### ISSUE THREAD

**Issue by DRosemei** [VITA-Group/SinNeRF#2]
Thanks for your great work. I want to know how you train DS-NeRF from a single view. DS-NeRF needs structure-from-motion to aquire 3D sparse points. Thanks in advance!
![image](https://user-images.githubusercontent.com/27892562/162873158-34541d6d-8dd4-4cf2-afbc-1162945ada90.png)

**Comment by Ir1d** [comment]
We use a dense depth map instead of sparse points for all experiments. In the original implementation of DS-NeRF, depth supervision is implemented as a list of rays with depth loss. In our experiments, we simply add depth supervision on all the rays.
