### ISSUE TITLE
Forward warping

### ISSUE THREAD

**Issue by ChaoyiZh** [VITA-Group/SinNeRF#20]
Dear author 
Thank you for your great work. And I am trying to incorporate your work into my pipeline. I found a problem that you use forward  warping to get the new RGB information and the new depth. But according to my understanding, forward warping will create holes and loss accuracy. Please point it out if I am wrong. If you stick to the plan I mentioned, how do you solve the problem related with forward warping? Thank you so much!

**Comment by Ir1d** [comment]
Yes, there will be holes. We didn't do interpolation or inpainting and only supervised the available pixels that are non zero

**Comment by ChaoyiZh** [comment]
Thank you for your response. Considering your application, you did not change a lot between the direction of the reference and warping view, so I don't think holes will be a big problem. However, if I want to generalize it to big direction change, the holes will be a big problem. And I don't think interpolation can can solve it. Could you please give me some suggestions?

**Comment by Ir1d** [comment]
How large is your change in viewing direction?

**Comment by ChaoyiZh** [comment]
The biggest one is 90 degree

**Comment by skyir0n** [comment]
I appreciate your sharing of the great work. I have a question. I have been trying to reproduce your work. On the LLFF dataset, however, I can't obtain a reliable warping image by using the depth maps you provided on this website. The warping error seems critical when comparing the warped and target images. Is there an additional process such as depth scaling? If so, please let me know.
