### ISSUE TITLE
Testing poses for the result videos

### ISSUE THREAD

**Issue by ayclove** [VITA-Group/SinNeRF#22]
Thanks again for your great work.
Did you provide testing poses for the result videos somewhere in your code?
If so, please let me know where I can find it.
Thanks for your answer in advance.

**Comment by Ir1d** [comment]
they are in the dataloader files. let me know if you still can't locate them

**Comment by ayclove** [comment]
Would you please point out the specific location?
For example I would like to know the testing poses for the below results.
[https://user-images.githubusercontent.com/10709657/161841696-b88f5797-6fd0-4f5c-a661-dd2802a12ac7.gif](url)
[https://user-images.githubusercontent.com/10709657/161841788-0baebb06-0375-48c6-8cc1-b00c796967db.gif](url)

Thank you in advance.

**Comment by Ir1d** [comment]
@ayclove Sorry that the code is a bit messy, but the idea is that we can rotate the camera pose matrix along a certain axis
like this:
https://github.com/VITA-Group/SinNeRF/blob/master/datasets/blender_ray_patch_1image_proj.py#L308

For Blender, I used the above rotation functions; for llff I used https://github.com/VITA-Group/SinNeRF/blob/master/datasets/llff_ray_patch_1image_proj.py#L244 ; for dtu i interpolated between the nearby camera poses
