### ISSUE TITLE
how to generate depth of LLFF dataset

### ISSUE THREAD

**Issue by violet257** [VITA-Group/SinNeRF#24]
Hi, Thanks for your amazing work.
I  wonder how to generate your depth map of LLFF dataset?
Since  for LLFF dataset, you provide depth of 5 scenes, could you please provide other 3 scenes? Or method for produce same depth?

**Comment by Ir1d** [comment]
Hi @violet257, Thanks for pointing out. We used a pretrained NeRF to render the depth on LLFF dataset. Also note that we didn't use NDC for LLFF
