### ISSUE TITLE
How many scans are used to evaluate on DTU?

### ISSUE THREAD

**Issue by TrickyGo** [VITA-Group/SinNeRF#26]
Thanks for sharing your excellent work! 
I want to know How many scenes are used to evaluate on DTU dataset and what are the scenes indexes? (In your paper. Table.2 "We report average values across scenes")
It will be a huge convenience for me to know so that I can compare with the reported scores, thanks in advance!!!

**Comment by Ir1d** [comment]
Hi @TrickyGo, Thanks for your interest. The scans I used are in the [depth map zip file](https://drive.google.com/file/d/176myZcKZwiJzwlokWAOvMl4tcT2yEjH2/view?usp=share_link). 

```
scan1    scan105  scan15  scan30  scan4   scan5   scan6   scan63  scan82  scan9  scan103  scan14   scan3   scan34  scan40  scan55  scan60  scan8   scan84
```

Hope it helps!

**Comment by TrickyGo** [comment]
Get it! Thanks a loooooooot!
