### ISSUE TITLE
How do I train SinNeRF with my own single RGBD image?

### ISSUE THREAD

**Issue by yifanlu0227** [VITA-Group/SinNeRF#28]
Thanks for your work!

I wonder how can I train a SinNeRF model with a single RGB-D image? There is no pose information. 

If I need to modify the code of dataset class, which file is the most convenient for me to modify?Thank you for your help.

**Comment by Ir1d** [comment]
Hi @yifanlu0227 , you can set the camera to be identity matrix. To do this, you need to modify the dataloader part
