### ISSUE TITLE
Unseen views during training

### ISSUE THREAD

**Issue by taeyeopl** [VITA-Group/SinNeRF#29]
Can you explain why the DTU only uses the 10 nearby cameras instead of random surrounding views like the LLFF dataset?
Is there any reason to use the existing camera poses during training for the DTU dataset?
I could understand using existing camera poses for evaluation but I haven't understood clearly for training.
```
[Paper]
LLFF Dataset: We randomly select a single view as the reference view and use its surrounding views as unseen views during training.
DTU Dataset: We use 10 nearby cameras from the dataset as unseen views during training.
```

**Comment by Ir1d** [comment]
Hi @taeyeopl it's easier to implement, there's no specific reason. At that time, we had some issues with generating random surrounding views so we chose to use available cameras instead.
