### ISSUE TITLE
Question about the rectified DTU dataset.

### ISSUE THREAD

**Issue by pansanity666** [VITA-Group/SinNeRF#30]
Hi, 
    I have found that your used DTU seems to be different from the commonly used one by pixelNeRF, DietNeRF, etc. Specifically, the images seems to be closer than the standard one. 
e.g.: 
standard scan8 cam0:
![image](https://github.com/VITA-Group/SinNeRF/assets/47111102/fb14d1a2-53e9-4661-99c4-2029c08b1ea0)

yours:
![image](https://github.com/VITA-Group/SinNeRF/assets/47111102/860fabcb-fed1-4439-bab6-c2c463938e0f)

May I ask how did you preprocess the DTU dataset? Did you crop the image? This is important for me to perform fair comparisons. 

Best,

**Comment by Ir1d** [comment]
HI @pansanity666 , If I remember correctly, I used https://github.com/xy-guo/MVSNet_pytorch to obtain depth on the DTU dataset. So I assume my DTU dataset was downloaded from their codebase as well. https://github.com/xy-guo/MVSNet_pytorch#training  I didn't do any further processing for the images.

Hope this helps!
