### ISSUE TITLE
problems in load vit

### ISSUE THREAD

**Issue by dlutzzw** [VITA-Group/SinNeRF#6]
Hi, thank for your exciting work,but When I tried to train in the room scene, I had the following problems when loading the VIT model, could you give me some suggestions?

~/NeRFs/SinNeRF$ 
python train.py  --dataset_name llff_ray_patch_1image_proj  --root_dir  data/nerf_llff_data/room   --N_importance 64 --img_wh 504 378 --num_epochs 3000 --batch_size 1  --optimizer adam --lr 2e-4  --lr_scheduler steplr --decay_step 1000 2000 --decay_gamma 0.5  --exp_name llff_room_s4 --with_ref --patch_size_x 63 --patch_size_y 84 --sW 4 --sH 4 --proj_weight 1 --depth_smooth_weight 0  --dis_weight 0 --num_gpus 4 --load_depth --depth_type nerf --model sinnerf --depth_weight 8 --vit_weight 10
Namespace(N_importance=64, N_samples=64, angle=30, batch_size=1, chunk=32768, ckpt_path=None, dataset_name='llff_ray_patch_1image_proj', decay_gamma=0.5, decay_step=[1000, 2000], depth_anneal=False, depth_smooth_weight=0.0, depth_type='nerf', depth_weight=8.0, dis_weight=0.0, dloss='hinge', exp_name='llff_room_s4', img_wh=[504, 378], load_depth=True, loss_type='mse', lr=0.0002, lr_scheduler='steplr', model='sinnerf', momentum=0.9, nH=32, nW=32, nerf_only=False, noise_std=1.0, num_epochs=3000, num_gpus=4, optimizer='adam', patch_loss='mse', patch_size=-1, patch_size_x=63, patch_size_y=84, perturb=1.0, poly_exp=0.9, prefixes_to_ignore=['loss'], proj_weight=1.0, pt_model=None, repeat=1, root_dir='data/nerf_llff_data/room', sH=4, sW=4, scan=4, spheric_poses=False, use_disp=False, vit_weight=10.0, warmup_epochs=0, warmup_multiplier=1.0, weight_decay=0, with_ref=True)
Using cache found in /home/zhangzhongwei18/.cache/torch/hub/facebookresearch_dino_main
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    system = SinNeRF(hparams)
  File "/home/zhangzhongwei18/NeRFs/SinNeRF/models/sinnerf.py", line 148, in __init__
    self.ext = VitExtractor(
  File "/home/zhangzhongwei18/NeRFs/SinNeRF/models/extractor.py", line 22, in __init__
    self.model = torch.hub.load(
  File "/home/zhangzhongwei18/.custom/cuda-10.2-cudnn8-devel-ubuntu18.04-pytorch1.8.0_full_tensorboard/envs/sinnerf/lib/python3.8/site-packages/torch/hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/zhangzhongwei18/.custom/cuda-10.2-cudnn8-devel-ubuntu18.04-pytorch1.8.0_full_tensorboard/envs/sinnerf/lib/python3.8/site-packages/torch/hub.py", line 430, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/zhangzhongwei18/.custom/cuda-10.2-cudnn8-devel-ubuntu18.04-pytorch1.8.0_full_tensorboard/envs/sinnerf/lib/python3.8/site-packages/torch/hub.py", line 76, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhangzhongwei18/.cache/torch/hub/facebookresearch_dino_main/hubconf.py", line 17, in <module>
    import vision_transformer as vits
  File "/home/zhangzhongwei18/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 24, in <module>
    from utils import trunc_normal_
ImportError: cannot import name 'trunc_normal_' from 'utils' (/home/zhangzhongwei18/NeRFs/SinNeRF/utils/__init__.py)

**Comment by Ir1d** [comment]
it seems to be some loading issue. maybe try modifying the `/home/zhangzhongwei18/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py` to make it work

**Comment by dlutzzw** [comment]
> it seems to be some loading issue. maybe try modifying the `/home/zhangzhongwei18/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py` to make it work

ok,thanks for your reply ,I've solved this problem by referring to this: https://github.com/ultralytics/yolov5/issues/2414

**Comment by Ir1d** [comment]
Thanks for letting me know!

**Comment by OvOtoQAQ** [comment]
Hi, sorry to bother you. I have a excatly same issue as yours and I'm a freshman so that it's really hard for me to fix it, could you please show me more details about how to modify the code? I'd appreciate it if you can write back, all the best:)

**Comment by OvOtoQAQ** [comment]
> 

It seems that when running 
``` from utils import trunc_normal_``` in ``` /home/wsh/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py```
it should have called ```utils.py``` in ``` /home/wsh/.cache/torch/hub/facebookresearch_dino_main/utils.py```
but actually it called this folder ```/home/wsh/SinNeRF/utils``` 
resulting in ```ImportError: cannot import name 'trunc_normal_' from 'utils' (/home/wsh/SinNeRF/utils/__init__.py) ```
@Ir1d have you ever met this issue before? Could you please show me how to fix it? all the best:)

**Comment by OvOtoQAQ** [comment]
> 

I add 
```import sys
   sys.modules.pop('utils')```  in ```torch/hub/facebookresearch_dino_main/vision_transformer.py``` 
before ```from utils import trunc_normal_```
it seems alright but I don't know whether it's correct, how did you fix it? please show me if it's possible, all the best:)

**Comment by OvOtoQAQ** [comment]
I add 
   ```sys.modules.pop('utils')```  in ```torch/hub/facebookresearch_dino_main/vision_transformer.py``` 
before ```from utils import trunc_normal_```
it seems alright but I don't know whether it's correct, how did you fix it? please show me if it's possible, all the best:)

**Comment by Ir1d** [comment]
one way is to rename the utils.py in facebookresearch_dino_main directory

**Comment by OvOtoQAQ** [comment]
> one way is to rename the utils.py in facebookresearch_dino_main directory

I tried 
```import sys
    sys.path.append('path') 
```
still cannot import...... maybe it's just supposed to be popped.......
thank you very much for replying to me:)

**Comment by Ir1d** [comment]
Have you tried this?
1. rename utils.py to vit_utils.py in facebookresearch_dino_main directory
2. change `from utils import ` to `from vit_utils import `

**Comment by OvOtoQAQ** [comment]
> Have you tried this?
> 
> 1. rename utils.py to vit_utils.py in facebookresearch_dino_main directory
> 2. change `from utils import ` to `from vit_utils import `

not yet, but as it all goes well now I dare not to change anything. 
I think maybe it's about module remaining in cache or something like that as mentioned before [yolov5/issues/2414](https://github.com/ultralytics/yolov5/issues/2414)
rather than path issue nor reuse name problem, since pop works well, I think it's good to just pop the utils out :)

**Comment by densechen** [comment]
Rename `utils` in this folder.

**Comment by yochananscharf** [comment]
Happened to me when I had another directory called `utils` that had ben imported.
