### ISSUE TITLE
AttributeError: 'LightningDistributedDataParallel' object has no attribute '_sync_params'

### ISSUE THREAD

**Issue by SEJUNHONG** [VITA-Group/SinNeRF#7]
I got the same error as the title.

I think it's a library version issue like pytorch, so could you tell me the versions of your libraries?

**Comment by Ir1d** [comment]
seems to be an issue with pytorch lightning. I believe I used 0.10. please see the environment.yml file

**Comment by OvOtoQAQ** [comment]
Hi, have you solved this problem? I have the same issue and I use pytorch lightning0.10.0, but this error didn't disappear, could you please show me how you fix it? all the best:)

**Comment by Ir1d** [comment]
@OvOtoQAQ did u remove other versions of lightning

**Comment by OvOtoQAQ** [comment]
> @OvOtoQAQ did u remove other versions of lightning

@Ir1d yeah, I think so. I've tried 3 different virtual environments and all kinds of combination, I usually first install lightning==0.10.0 then install torch compatable with cuda11.4, but it always raises an error:(

**Comment by Ir1d** [comment]
I think I have tested on cuda10.2 and cuda11.1 before but not on 11.4

**Comment by OvOtoQAQ** [comment]
> I think I have tested on cuda10.2 and cuda11.1 before but not on 11.4

I install cuda11.1 and finally it begins to train! Maybe it's all about fortune.
for who may face the same issue:
you should first make sure your torch compatible with lightning 0.10
for cuda11.1 I use torch==1.10
and you should set ```num_workers=0``` in ```sinnerf.py``` 
if  ```RuntimeError:DataLoader worker (pid *** ***) exited``` occurs

anyway, thanks for your patience, wish you all the best:)

**Comment by Wanggcong** [comment]
> I think I have tested on cuda10.2 and cuda11.1 before but not on 11.4

It seems the problem still exists, I used your command "pip install -r requirement.txt", I checked the version in the python command environment:
 >>> torch.__version__
'1.12.1+cu102'
