### ISSUE TITLE
Where can I find supplementary materials

### ISSUE THREAD

**Issue by zcm2w0116** [VITA-Group/SinNeRF#8]
Thank you for the good work and providing the code.

Where can I find the supplementary materials mentioned in the paper?

**Comment by Ir1d** [comment]
I believe everything in the supplementary material has been released either on the project page or in this repo. Is there anything specific missing?

**Comment by zcm2w0116** [comment]
> I believe everything in the supplementary material has been released either on the project page or in this repo. Is there anything specific missing?

Thank you for your prompt reply ！

![image](https://user-images.githubusercontent.com/49070981/169468263-d4b2debc-dfec-4308-a06a-bf047a92434a.png)
![image](https://user-images.githubusercontent.com/49070981/169468365-ce5bae53-2df4-4a6b-8d50-69ada8667b75.png)

As shown above, it is the supplementary material mentioned in the paper.

I don't know where to find it. If you can, please tell where to find it, I would be very grateful！

**Comment by Ir1d** [comment]
the implementations are provided in the code. the results are on the webpage
