### ISSUE TITLE
GPU environments

### ISSUE THREAD

**Issue by SEJUNHONG** [VITA-Group/SinNeRF#9]
Hi
I encountered the problem that CUDA out of memory.
My gpu spec is GeForce RTX 2080 Ti.
And I'm using DDP.

Could you tell me your gpu spec?
Also, I would appreciate it if you could tell me how to make a depth image .npy files.

**Comment by Ir1d** [comment]
Hi,

I'm using A6000 GPU. Maybe you can try the steps I mentioned in the README.
.npy files contain float values of depth
